### ISSUE TITLE
ClassCastException writing Excel file

### ISSUE THREAD

**Issue by baum-sparton** [centic9/poi-on-android#105]
I'm getting a strange exception when using the library.  See the stack below.  It seems odd MediaControllerCompat is being called within POI.

org.apache.poi.ooxml.POIXMLException: java.lang.ClassCastException
	at org.apache.poi.ooxml.POIXMLDocumentPart.createRelationship(POIXMLDocumentPart.java:608)
	at org.apache.poi.ooxml.POIXMLDocumentPart.createRelationship(POIXMLDocumentPart.java:502)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:488)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:232)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:226)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:214)
	at com.my.reporting.ExcelFileWriter.createExcelFileForPersonnel(ExcelFileWriter.java:141)
	at com.my.reporting.ExportReportWorker.doWork(ExportReportWorker.java:71)
	at androidx.work.Worker$1.run(Worker.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassCastException
	at android.support.v4.media.session.MediaControllerCompat$MediaControllerImplApi21$ExtraBinderRequestResultReceiver$$ExternalSyntheticThrowCCEIfNotNull0.m(R8$$SyntheticClass:0)
	at org.openxmlformats.schemas.spreadsheetml.x2006.main.impl.CTFontImpl.addNewFamily(CTFontImpl.java:346)
	at org.apache.poi.xssf.usermodel.XSSFFont.setFamily(XSSFFont.java:649)
	at org.apache.poi.xssf.usermodel.XSSFFont.setFamily(XSSFFont.java:661)
	at org.apache.poi.xssf.model.StylesTable.createDefaultFont(StylesTable.java:795)
	at org.apache.poi.xssf.model.StylesTable.initialize(StylesTable.java:746)
	at org.apache.poi.xssf.model.StylesTable.<init>(StylesTable.java:150)
	at org.apache.poi.xssf.usermodel.XSSFRelation$$ExternalSyntheticLambda16.init(R8$$SyntheticClass:0)
	at org.apache.poi.ooxml.POIXMLFactory.newDocumentPart(POIXMLFactory.java:94)
	at org.apache.poi.ooxml.POIXMLDocumentPart.createRelationship(POIXMLDocumentPart.java:593)
	at org.apache.poi.ooxml.POIXMLDocumentPart.createRelationship(POIXMLDocumentPart.java:502) 
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:488) 
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:232) 
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:226) 
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:214) 
	at com.my.reporting.ExcelFileWriter.createExcelFileForPersonnel(ExcelFileWriter.java:141) 
	at com.my.reporting.ExportReportWorker.doWork(ExportReportWorker.java:71) 
	at androidx.work.Worker$1.run(Worker.java:82) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
	at java.lang.Thread.run(Thread.java:919)

**Comment by centic9** [comment]
Very hard to investigate without any indication of what you are differently than the provided sample application poitest. Anything that you do differently here?

**Comment by baum-sparton** [comment]
As far as I know I'm not doing anything special or different in my app than others.

If I look at the source code at CTFontImpl.java:346 I see a cast occurring to type org.openxmlformats.schemas.spreadsheetml.x2006.main.CTFontFamily.  I don't see this class listed in the ProGuard file.  So I'm suspecting that perhaps there are some additional ProGuard rules that need added.  I'm going to add a rule for the class and see where that takes me.  I'll post an update after I see what that gets me.

**Comment by baum-sparton** [comment]
The issue was with R8 stripping out stuff.  Specifically, related to the XML schema.  Rather than using the ProGuard file in the project, I used the following.  These rules are less specific, but hopefully easier to maintain.

-keep,allowoptimization,allowobfuscation class org.apache.logging.log4j.** { *; }
-keep,allowoptimization class org.apache.commons.compress.archivers.zip.** { *; }
-keep,allowoptimization class org.apache.poi.schemas.** { *; }
-keep,allowoptimization class org.apache.xmlbeans.** { *; }
-keep,allowoptimization class com.microsoft.schemas.** { *; }
-keep,allowoptimization class org.openxmlformats.schemas.** { *; }
-dontwarn com.microsoft.schemas.**
-dontwarn java.awt.**
-dontwarn javax.xml.stream.XMLStreamReader
-dontwarn net.sf.saxon.**
-dontwarn org.apache.batik.**
-dontwarn org.apache.logging.log4j.**
-dontwarn org.apache.xmlbeans.**
-dontwarn org.openxmlformats.schemas.**

**Comment by centic9** [comment]
Thanks for the details, I did some changes to the rules that are used in the sample app.
