### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Color;

### ISSUE THREAD

**Issue by jack7277** [centic9/poi-on-android#30]
Hello. I'm using Android Studio 3.0.x, and imported your poishadow-all.jar v0.5
I tried my own code of importing excel from POI 3.12 to your version and it's works quite fine,
but when I tried to import MPP file using MPXJ 7.2.1 I got that I don't have a library and crash.

I saw your solution, spent a lot of hours, but I don't understand how to override awt/Color with your solution. Please, help.

Crash on read:
MPPReader reader = new MPPReader();
String path2file = context.getFilesDir() + "/" +SAMPLE21_MPPX;
ProjectFile projectFile = reader.read(path2file);

here is full error:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.bio.tj, PID: 13427
                  java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Color;
                      at net.sf.mpxj.mpp.MPPUtility.getColor(MPPUtility.java:543)
                      at net.sf.mpxj.mpp.GanttChartView14.getFontStyle(GanttChartView14.java:258)
                      at net.sf.mpxj.mpp.GanttChartView14.processViewProperties(GanttChartView14.java:143)
                      at net.sf.mpxj.mpp.GanttChartView.<init>(GanttChartView.java:140)
                      at net.sf.mpxj.mpp.GanttChartView14.<init>(GanttChartView14.java:403)
                      at net.sf.mpxj.mpp.ViewFactory14.createView(ViewFactory14.java:56)
                      at net.sf.mpxj.mpp.MPP14Reader.processViewData(MPP14Reader.java:1790)
                      at net.sf.mpxj.mpp.MPP14Reader.process(MPP14Reader.java:104)
                      at net.sf.mpxj.mpp.MPPReader.read(MPPReader.java:158)
                      at net.sf.mpxj.mpp.MPPReader.read(MPPReader.java:80)
                      at net.sf.mpxj.reader.AbstractProjectReader.read(AbstractProjectReader.java:49)
                      at com.example.bio.tj.Parsers.ParserMPPX.parseMPPX_importToPTS(ParserMPPX.java:21)
                      at com.example.bio.tj.MainActivity.onButtonGetProjectMPPXClick(MainActivity.java:1370)
                      at com.example.bio.tj.MainActivity_ViewBinding$12.doClick(MainActivity_ViewBinding.java:147)
                      at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                      at android.view.View.performClick(View.java:4756)
                      at android.view.View$PerformClick.run(View.java:19749)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5221)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.Color" on path: DexPathList[[zip file "/data/app/com.example.bio.tj-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.bio.tj-2/lib/x86_64, /vendor/lib64, /system/lib64]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at net.sf.mpxj.mpp.MPPUtility.getColor(MPPUtility.java:543) 
                      at net.sf.mpxj.mpp.GanttChartView14.getFontStyle(GanttChartView14.java:258) 
                      at net.sf.mpxj.mpp.GanttChartView14.processViewProperties(GanttChartView14.java:143) 
                      at net.sf.mpxj.mpp.GanttChartView.<init>(GanttChartView.java:140) 
                      at net.sf.mpxj.mpp.GanttChartView14.<init>(GanttChartView14.java:403) 
                      at net.sf.mpxj.mpp.ViewFactory14.createView(ViewFactory14.java:56) 
                      at net.sf.mpxj.mpp.MPP14Reader.processViewData(MPP14Reader.java:1790) 
                      at net.sf.mpxj.mpp.MPP14Reader.process(MPP14Reader.java:104) 
                      at net.sf.mpxj.mpp.MPPReader.read(MPPReader.java:158) 
                      at net.sf.mpxj.mpp.MPPReader.read(MPPReader.java:80) 
                      at net.sf.mpxj.reader.AbstractProjectReader.read(AbstractProjectReader.java:49) 
                      at com.example.bio.tj.Parsers.ParserMPPX.parseMPPX_importToPTS(ParserMPPX.java:21) 
                      at com.example.bio.tj.MainActivity.onButtonGetProjectMPPXClick(MainActivity.java:1370) 
                      at com.example.bio.tj.MainActivity_ViewBinding$12.doClick(MainActivity_ViewBinding.java:147) 
                      at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22) 
                      at android.view.View.performClick(View.java:4756) 
                      at android.view.View$PerformClick.run(View.java:19749) 
                      at android.os.Handler.handleCallback(Handler.java:739) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5221) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
                  	Suppressed: java.lang.ClassNotFoundException: java.awt.Color
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                      		... 26 more
                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by jack7277** [comment]
When I tried to run it on android 4.4.2, I got (it's strange) because it works fine on android 5.

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lorg/apache/poi/java/awt/Color;
Error:com.android.dex.DexException: Multiple dex files define Lorg/apache/poi/java/awt/Color;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lorg/apache/poi/java/awt/Color;

**Comment by jack7277** [comment]
close, please

https://stackoverflow.com/questions/48937516/reading-parsing-ms-project-mpp-java-android-5-0

**Comment by centic9** [comment]
Ok, anyway this is unrelated to this project anyway.
