### ISSUE TITLE
Caused by: java.io.IOException: Failed to read zip entry source

### ISSUE THREAD

**Issue by donglp1810** [centic9/poi-on-android#33]
I run your poitest app. And get this::

03-09 10:08:43.641 24947-24947/org.dstadler.poiandroidtest.poitest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: org.dstadler.poiandroidtest.poitest, PID: 24947
                                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{org.dstadler.poiandroidtest.poitest/org.dstadler.poiandroidtest.poitest.DocumentListActivity}: java.lang.IllegalStateException: java.io.IOException: Failed to read zip entry source
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2326)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5264)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
                                                                                      Caused by: java.lang.IllegalStateException: java.io.IOException: Failed to read zip entry source
                                                                                         at org.dstadler.poiandroidtest.poitest.DocumentListActivity.onCreate(DocumentListActivity.java:119)
                                                                                         at android.app.Activity.performCreate(Activity.java:5975)
                                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5264) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695) 
                                                                                      Caused by: java.io.IOException: Failed to read zip entry source
                                                                                         at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:103)
                                                                                         at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
                                                                                         at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
                                                                                         at org.apache.poi.xwpf.usermodel.XWPFDocument.<init>(XWPFDocument.java:116)
                                                                                         at org.dstadler.poiandroidtest.poitest.DocumentListActivity.onCreate(DocumentListActivity.java:106)
                                                                                         at android.app.Activity.performCreate(Activity.java:5975) 
                                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269) 
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5264) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695) 
                                                                                      Caused by: java.util.zip.ZipException: invalid distance too far back
                                                                                         at java.util.zip.ZipInputStream.read(ZipInputStream.java:339)
                                                                                         at org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream.read(ZipSecureFile.java:219)
                                                                                         at java.io.InputStream.read(InputStream.java:162)
                                                                                         at org.apache.poi.openxml4j.util.ZipInputStreamZipEntrySource$FakeZipEntry.<init>(ZipInputStreamZipEntrySource.java:132)
                                                                                         at org.apache.poi.openxml4j.util.ZipInputStreamZipEntrySource.<init>(ZipInputStreamZipEntrySource.java:56)
                                                                                         at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:100)
                                                                                         at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324) 
                                                                                         at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37) 
                                                                                         at org.apache.poi.xwpf.usermodel.XWPFDocument.<init>(XWPFDocument.java:116) 
                                                                                         at org.dstadler.poiandroidtest.poitest.DocumentListActivity.onCreate(DocumentListActivity.java:106) 
                                                                                         at android.app.Activity.performCreate(Activity.java:5975) 
                                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105) 
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269) 
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5264) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695) 

Error from this code : 

 InputStream docFile = getResources().openRawResource(R.raw.lorem_ipsum);
            try {
                XWPFDocument doc = new XWPFDocument(docFile);
                try {
                    for(XWPFParagraph paragraph : doc.getParagraphs()) {
                        DummyContent.addItem(new DummyContent.DummyItem(Integer.toString(i), StringUtils.abbreviate(paragraph.getText(), 20), paragraph.getText()));
                        i++;
                    }
                } finally {
                    doc.close();
                }
            } finally {
                docFile.close();
            }
in DocumentListActivity.Java File

Seem cant read InputStream from your "lorem_ipsum" raw
Please help me fix this issue. Thanks for  your help

**Comment by centic9** [comment]
This looks like some problem outside of the poi-related code, i.e. either the file is corrupted on your phone or the reading/opening of the file is not valid, I don't see where I can help you here...

The error-message is something like "Caused by: java.util.zip.ZipException: invalid distance too far back" here, which indicates that the base ZIP code cannot unzip the document that you are trying to open.

I would check the openRawResoruce() code and check if the correct docx-data is returned here, as it seems some other data is actually returned here in your case.

**Comment by centic9** [comment]
I don't think this is caused by this project, please reopen if you have more information.
