### ISSUE TITLE
Provider com.fasterxml.aalto.stax.EventFactoryImpl not found when use android:sharedUserId

### ISSUE THREAD

**Issue by xinvestoriginal** [centic9/poi-on-android#35]
Good afternoon. I built your test project with the poishadow-all.jar library and it works great. But if I add in AndroidManifest.xml android: sharedUserId = "org.dstadler.poiandroidtest.poitest" to the 4th line - an error occurs:

05-04 15:29:38.758 8690-8690/org.dstadler.poiandroidtest.poitest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.dstadler.poiandroidtest.poitest, PID: 8690
    org.apache.poi.javax.xml.stream.FactoryConfigurationError: Provider com.fasterxml.aalto.stax.EventFactoryImpl not found
        at org.apache.poi.javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
        at org.apache.poi.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:120)
        at org.apache.poi.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
        at org.apache.poi.javax.xml.stream.XMLEventFactory.newInstance(XMLEventFactory.java:30)
        at org.apache.poi.openxml4j.opc.internal.marshallers.PackagePropertiesMarshaller.<clinit>(PackagePropertiesMarshaller.java:41)
        at org.apache.poi.openxml4j.opc.OPCPackage.init(OPCPackage.java:161)
        at org.apache.poi.openxml4j.opc.OPCPackage.<init>(OPCPackage.java:141)
        at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:72)
        at org.apache.poi.openxml4j.opc.OPCPackage.create(OPCPackage.java:394)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.newPackage(XSSFWorkbook.java:480)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:247)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:239)
        at org.dstadler.poiandroidtest.poitest.DocumentListActivity.writeWorkbook(DocumentListActivity.java:171)
        at org.dstadler.poiandroidtest.poitest.DocumentListActivity.onCreate(DocumentListActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:6955)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

Is it possible to fix this error?

**Comment by imzhq** [comment]
I got same error , try this 
Thread.currentThread().setContextClassLoader(epApplication.getClassLoader());
// your action                                  
Thread.currentThread().setContextClassLoader(oldClassLoader);

**Comment by fazakasc** [comment]
I face the same issue, after adding the shareduserid to androidmanifest.xml, I get error "com.fasterxml.aalto.stax.EventFactoryImpl not found". Any fix for this? How/where can be used the above mentioned solution ?

**Comment by centic9** [comment]
Please check with the latest version and verify that you did set the system-properties as described in the ![README](https://github.com/centic9/poi-on-android/blob/master/README.md#necessary-system-properties). 

With those this should not happen any more.

If you still see this error, please reopen with some more information about how this can be reproduced.
