### ISSUE TITLE
Error on evaluator on AsyncTask android Pie

### ISSUE THREAD

**Issue by GuidoChia** [centic9/poi-on-android#49]
Hey I'm using an formula evaluator, and while running on the main thread it works as it should. But when on a AsyncTask, I got a RuntimeException and a almost infinite stack trace. This is happening in android Pie, but in Android 5.1 it works well. Any known issues on this?

Thanks!

**Comment by GuidoChia** [comment]
2019-01-21 15:34:20.041 29986-30027/skrb.appprueba E/AndroidRuntime:     at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateFormula(WorkbookEvaluator.java:514)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateAny(WorkbookEvaluator.java:278)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateReference(WorkbookEvaluator.java:714)
        at org.apache.poi.ss.formula.SheetRefEvaluator.getEvalForCell(SheetRefEvaluator.java:48)
        at org.apache.poi.ss.formula.SheetRangeEvaluator.getEvalForCell(SheetRangeEvaluator.java:74)
        at org.apache.poi.ss.formula.LazyRefEval.getInnerValueEval(LazyRefEval.java:39)
        at org.apache.poi.ss.formula.eval.OperandResolver.chooseSingleElementFromRef(OperandResolver.java:179)
        at org.apache.poi.ss.formula.eval.OperandResolver.getSingleValue(OperandResolver.java:62)
        at org.apache.poi.ss.formula.eval.TwoOperandNumericOperation.singleOperandEvaluate(TwoOperandNumericOperation.java:29)
        at org.apache.poi.ss.formula.eval.TwoOperandNumericOperation.evaluate(TwoOperandNumericOperation.java:36)
        at org.apache.poi.ss.formula.functions.Fixed2ArgFunction.evaluate(Fixed2ArgFunction.java:33)
        at org.apache.poi.ss.formula.OperationEvaluatorFactory.evaluate(OperationEvaluatorFactory.java:119)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateFormula(WorkbookEvaluator.java:514)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateAny(WorkbookEvaluator.java:278)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluate(WorkbookEvaluator.java:220)
        at org.apache.poi.hssf.usermodel.HSSFFormulaEvaluator.evaluateFormulaCellValue(HSSFFormulaEvaluator.java:200)
        at org.apache.poi.ss.formula.BaseFormulaEvaluator.evaluate(BaseFormulaEvaluator.java:101)
        at reader.ConcreteReader.convertToCustomer(ConcreteReader.java:211)
        at reader.ConcreteReader.readCostumersFromSubFolder(ConcreteReader.java:145)
        at reader.ConcreteReader.readCostumers(ConcreteReader.java:123)
        at reader.ConcreteReader.readCostumersMonth(ConcreteReader.java:79)
        at skrb.appprueba.RouteTask.doInBackground(RouteTask.java:62)
        at skrb.appprueba.RouteTask.doInBackground(RouteTask.java:27)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        	... 4 more
2019-01-21 15:34:20.046 29986-30027/skrb.appprueba E/AndroidRuntime:     at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateFormula(WorkbookEvaluator.java:514)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateAny(WorkbookEvaluator.java:278)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateReference(WorkbookEvaluator.java:714)
        at org.apache.poi.ss.formula.SheetRefEvaluator.getEvalForCell(SheetRefEvaluator.java:48)
        at org.apache.poi.ss.formula.SheetRangeEvaluator.getEvalForCell(SheetRangeEvaluator.java:74)
        at org.apache.poi.ss.formula.LazyRefEval.getInnerValueEval(LazyRefEval.java:39)
        at org.apache.poi.ss.formula.eval.OperandResolver.chooseSingleElementFromRef(OperandResolver.java:179)
        at org.apache.poi.ss.formula.eval.OperandResolver.getSingleValue(OperandResolver.java:62)
        at org.apache.poi.ss.formula.eval.TwoOperandNumericOperation.singleOperandEvaluate(TwoOperandNumericOperation.java:29)
        at org.apache.poi.ss.formula.eval.TwoOperandNumericOperation.evaluate(TwoOperandNumericOperation.java:36)
        at org.apache.poi.ss.formula.functions.Fixed2ArgFunction.evaluate(Fixed2ArgFunction.java:33)
        at org.apache.poi.ss.formula.OperationEvaluatorFactory.evaluate(OperationEvaluatorFactory.java:119)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateFormula(WorkbookEvaluator.java:514)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateAny(WorkbookEvaluator.java:278)
        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluate(WorkbookEvaluator.java:220)
        at org.apache.poi.hssf.usermodel.HSSFFormulaEvaluator.evaluateFormulaCellValue(HSSFFormulaEvaluator.java:200)
        at org.apache.poi.ss.formula.BaseFormulaEvaluator.evaluate(BaseFormulaEvaluator.java:101)
        at reader.ConcreteReader.convertToCustomer(ConcreteReader.java:211)
        at reader.ConcreteReader.readCostumersFromSubFolder(ConcreteReader.java:145)
        at reader.ConcreteReader.readCostumers(ConcreteReader.java:123)
        at reader.ConcreteReader.readCostumersMonth(ConcreteReader.java:79)
        at skrb.appprueba.RouteTask.doInBackground(RouteTask.java:62)
        at skrb.appprueba.RouteTask.doInBackground(RouteTask.java:27)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        	... 4 more

**Comment by GuidoChia** [comment]
The strange thing is that this only happen while running on an Async Task.
My AsyncTask class can be found here: https://github.com/GuidoChia/Venta-de-agua-TDP/blob/MoveAsyncTask/app/src/main/java/skrb/appprueba/RouteTask.java

**Comment by GuidoChia** [comment]
I'm using the last release of shadowpoi-all.jar, based on version 3.17.
No idea what is wrong

**Comment by GuidoChia** [comment]
So just tried on another phone, now running android 7.1.1. It works. Maybe something changed on how AsyncTask works on Pie?
