### ISSUE TITLE
Application hangs when loading XLSX file

### ISSUE THREAD

**Issue by anta40** [centic9/poi-on-android#56]
I'm trying to use this lib to read and write XLSX files.
Here's my code repo: https://github.com/anta40/StockChecker.

Some relevant parts:
**MainActivity.java**
```
package com.anta40.app.stockchecker;

import android.Manifest;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.ActivityCompat;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.Toast;

import com.github.angads25.filepicker.controller.DialogSelectionListener;
import com.github.angads25.filepicker.model.DialogConfigs;
import com.github.angads25.filepicker.model.DialogProperties;
import com.github.angads25.filepicker.view.FilePickerDialog;

import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Iterator;

public class MainActivity extends AppCompatActivity {

    Button btnPickFile;
    final int MY_REQUEST_CODE = 13245;
    final int PERMISSIONS_REQUEST_CODE = 0;
    final int FILE_PICKER_REQUEST_CODE = 1;
    FilePickerDialog dialog;
    Workbook wb;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        initFasterXML();

        btnPickFile = (Button) findViewById(R.id.btnPickFile);
        btnPickFile.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                DialogProperties properties = new DialogProperties();
                properties.selection_mode = DialogConfigs.SINGLE_MODE;
                properties.selection_type = DialogConfigs.FILE_SELECT;
                properties.root = new File(DialogConfigs.DEFAULT_DIR);
                properties.error_dir = new File(DialogConfigs.DEFAULT_DIR);
                properties.offset = new File(DialogConfigs.DEFAULT_DIR);
                properties.extensions = new String[] {"xlsx"};

                dialog = new FilePickerDialog(MainActivity.this,properties);
                dialog.setTitle("Select XLSX file");

                dialog.setDialogSelectionListener(new DialogSelectionListener() {
                    @Override
                    public void onSelectedFilePaths(String[] files) {
                        try {
                            int count = 0;
                            FileInputStream excelFile = new FileInputStream(new File(files[0]));
                            wb = new XSSFWorkbook(excelFile);
                            Sheet sheet = wb.getSheetAt(0);
                            Iterator<Row> rowIterator = sheet.iterator();

                            while (rowIterator.hasNext()){
                                count += 1;
                            }

                            excelFile.close();

                            Toast.makeText(getApplicationContext(), "Row count: "+count, Toast.LENGTH_SHORT).show();

                        }
                        catch (FileNotFoundException fnfe){
                            Toast.makeText(getApplicationContext(), fnfe.getMessage(), Toast.LENGTH_SHORT).show();
                        }
                        catch (IOException ioe){
                            Toast.makeText(getApplicationContext(), ioe.getMessage(), Toast.LENGTH_SHORT).show();
                        }
                    }
                });

                dialog.show();

            }
        });
    }

    private void initFasterXML(){
        System.setProperty("org.apache.poi.javax.xml.stream.XMLInputFactory", "com.fasterxml.aalto.stax.InputFactoryImpl");
        System.setProperty("org.apache.poi.javax.xml.stream.XMLOutputFactory", "com.fasterxml.aalto.stax.OutputFactoryImpl");
        System.setProperty("org.apache.poi.javax.xml.stream.XMLEventFactory", "com.fasterxml.aalto.stax.EventFactoryImpl");
    }
}
```

**build.gradle**
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28

    defaultConfig {
        applicationId "com.anta40.app.stockchecker"
        minSdkVersion 15
        targetSdkVersion 28
        multiDexEnabled true
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions{
        // exclude 'META-INF/DEPENDENCIES'  <--- and try commenting this out, I don't believe it should be needed
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        pickFirst 'META-INF/services/javax.xml.stream.XMLInputFactory'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.github.angads25:filepicker:1.1.1'
    implementation files('lib\\poishadow-all.jar')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

}
```

Every time the app tries to load XLSX file, it will hang. There's no usable hint at logcat. But, if initFasterXML() inside onCreate() is commented, app will crash. Here's the log:

> 2019-05-11 21:10:49.149 9824-9824/com.anta40.app.stockchecker E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.anta40.app.stockchecker, PID: 9824
>     org.apache.poi.javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.EventFactory not found
>         at org.apache.poi.javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
>         at org.apache.poi.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:178)
>         at org.apache.poi.javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
>         at org.apache.poi.javax.xml.stream.XMLEventFactory.newInstance(XMLEventFactory.java:30)
>         at org.apache.poi.openxml4j.opc.internal.marshallers.PackagePropertiesMarshaller.<clinit>(PackagePropertiesMarshaller.java:41)
>         at org.apache.poi.openxml4j.opc.OPCPackage.init(OPCPackage.java:161)
>         at org.apache.poi.openxml4j.opc.OPCPackage.<init>(OPCPackage.java:141)
>         at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:97)
>         at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
>         at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
>         at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:295)
>         at com.anta40.app.stockchecker.MainActivity$1$1.onSelectedFilePaths(MainActivity.java:69)
>         at com.github.angads25.filepicker.view.FilePickerDialog$1.onClick(FilePickerDialog.java:131)
>         at android.view.View.performClick(View.java:6266)
>         at android.view.View$PerformClick.run(View.java:24730)
>         at android.os.Handler.handleCallback(Handler.java:793)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:173)
>         at android.app.ActivityThread.main(ActivityThread.java:6698)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
> 2019-05-11 21:10:49.218 9824-9824/com.anta40.app.stockchecker I/Process: Sending signal. PID: 9824 SIG: 9
> 

I use Android Studio 3.4, and my device runs Android O.

**Comment by centic9** [comment]
Please read the main-page/README, especially the section "Necessary System-Properties".
