### ISSUE TITLE
Class 'org.apache.xmlbeans.impl.store.Cur' does not implement interface 'java.util.List' in call to 'int java.util.List.size()' 

### ISSUE THREAD

**Issue by Gowa2017** [centic9/poi-on-android#64]
Please, Help me, why I have this erro?
```
    java.lang.IncompatibleClassChangeError: Class 'org.apache.xmlbeans.impl.store.Cur' does not implement interface 'java.util.List' in call to 'int java.util.List.size()' (declaration of 'org.apache.xmlbeans.impl.store.Saver' appears in base.apk!classes5.dex)
        at org.apache.xmlbeans.impl.store.Saver.pushMappings(Saver.java:546)
        at org.apache.xmlbeans.impl.store.Saver.processElement(Saver.java:406)
        at org.apache.xmlbeans.impl.store.Saver.process(Saver.java:307)
        at org.apache.xmlbeans.impl.store.Saver.<init>(Saver.java:123)
        at org.apache.xmlbeans.impl.store.Saver$TextSaver.<init>(Saver.java:916)
        at org.apache.xmlbeans.impl.store.Saver$InputStreamSaver.<init>(Saver.java:2468)
        at org.apache.xmlbeans.impl.store.Cursor._newInputStream(Cursor.java:550)
        at org.apache.xmlbeans.impl.store.Cursor._save(Cursor.java:579)
        at org.apache.xmlbeans.impl.store.Cursor.save(Cursor.java:2544)
        at org.apache.xmlbeans.impl.values.XmlObjectBase.save(XmlObjectBase.java:223)
        at org.apache.poi.POIXMLProperties.commit(POIXMLProperties.java:225)
        at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:225)
        at cn.nanming.smartsupervision.core.manager.doc.DocManager.testTemplateWrite(DocManager.java:355)
        at cn.nanming.smartsupervision.ui.activity.microenterprisemanage.MicroApplicationDetailActivity.saveDoc(MicroApplicationDetailActivity.java:1194)
        at cn.nanming.smartsupervision.ui.activity.microenterprisemanage.MicroApplicationDetailActivity.access$2900(MicroApplicationDetailActivity.java:87)
        at cn.nanming.smartsupervision.ui.activity.microenterprisemanage.MicroApplicationDetailActivity$16.onResult(MicroApplicationDetailActivity.java:1229)
        at cn.nanming.smartsupervision.ui.activity.microenterprisemanage.MicroApplicationDetailActivity$16.onResult(MicroApplicationDetailActivity.java:1222)
        at cn.nanming.smartsupervision.core.requester.SimpleHttpRequester.onFinish(SimpleHttpRequester.java:47)
        at cn.nanming.smartsupervision.core.requester.HttpRequester$1.onSuccess(HttpRequester.java:72)
        at com.loopj.android.http.TextHttpResponseHandler.onSuccess(TextHttpResponseHandler.java:118)
        at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351)
        at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6990)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by centic9** [comment]
What exactly are you doing up to the point where you try to write the document to trigger this?

**Comment by Gowa2017** [comment]
what I do is in a XWPFDocument replaced some text, then I use  doc.wirte(os) method, then is crash.

```java
        CustomXWPFDocument doc = new CustomXWPFDocument(is);
        long time4 = System.currentTimeMillis();
        this.replaceInPara(doc, params);
        Log.d("nsh", "当前耗时4：" + (System.currentTimeMillis() - time4) / 1000);
        long time5 = System.currentTimeMillis();
        this.replaceInTable(doc, params);
        Log.d("nsh", "当前耗时5：" + (System.currentTimeMillis() - time5) / 1000);

        replaceInFooter(doc, params);
        OutputStream os = new FileOutputStream(targetPath);
        doc.write(os);
```

**Comment by Gowa2017** [comment]
Seems it is a xmlbeans problem. I use multidex keep file and set all xmlbeans relative class to the main class.dex,everything is ok.

**Comment by wenmin92** [comment]
I faced the same problem, and config the multidex like this, 
```
-keep class org.apache.xmlbeans.** {*;}
```
but, it didn't work.

**Comment by vik17ag** [comment]
You can refer to this link [http://myhexaville.com/2017/03/10/android-multidex/](url) to understand how to keep xmlbeans classes in main dex by using '

> multiDexKeepProguard 

'

**Comment by dinhvuhaui** [comment]
> class

Can you give more detailed instructions

**Comment by dinhvuhaui** [comment]
> Seems it is a xmlbeans problem. I use multidex keep file and set all xmlbeans relative class to the main class.dex,everything is ok.

Can you give more detailed instructions
