### ISSUE TITLE
Could support JAXB?

### ISSUE THREAD

**Issue by rockmany2000** [centic9/poi-on-android#80]
Hello Centic9,
It is a good project. I am porting XSLFSlide show in Android base your project. 
But I face the issue about JAXB. I found POI3.17 need JAXB in poi/sl/draw. JAXB is base on standard JDK ,but not in Android SDK .  I study many 3rd solutions (in stackoverflow) to port JAXB but not  successed.  

Did you have some suggestion or comment?

    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/poi/javax/xml/bind/JAXBContext;
        at org.apache.poi.sl.draw.geom.PresetGeometries.init(PresetGeometries.java:69)
        at org.apache.poi.sl.draw.geom.PresetGeometries.getInstance(PresetGeometries.java:111)
        at org.apache.poi.xslf.usermodel.XSLFSimpleShape.getGeometry(XSLFSimpleShape.java:722)
        at org.apache.poi.sl.draw.DrawSimpleShape.computeOutlines(DrawSimpleShape.java:402)
        at org.apache.poi.sl.draw.DrawSimpleShape.draw(DrawSimpleShape.java:76)
        at org.apache.poi.sl.draw.DrawSheet.draw(DrawSheet.java:71)
        at org.apache.poi.sl.draw.DrawSlide.draw(DrawSlide.java:41)
        at org.apache.poi.xslf.usermodel.XSLFSlide.draw(XSLFSlide.java:307)

**Comment by centic9** [comment]
Can you provide a simple example which triggers this exception? Otherwise it is hard to reproduce/analyze.
